---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/isort
    rev: master
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy
  - repo: https://github.com/exhuma/pre-commit-hooks
    rev: main
    hooks:
      - id: prevent-debug-markers
